from turtle import *
euler = Turtle()
euler.shape('turtle')
sherva = Turtle()
sherva.shape("turtle")
sherva.pensize(20)
euler.pensize(20)
def main():
    sherva.color('blue','yellow')
    sherva.begin_fill()
    euler.color('blue','yellow')
    euler.begin_fill()
    def euler_drwing(turtle):
        euler.penup()
        euler.backward(800)
        euler.pendown()
        for i in range(5):
            euler.left(144)
            euler.forward(50)
        euler.penup()
        euler.forward(100)
        euler.pendown()
        
        for i in range(5):
            euler.left(144)
            euler.forward(50)
        euler.penup()
        euler.forward(100)
        euler.pendown()
        for i in range(5):
            euler.left(144)
            euler.forward(50)
        euler.penup()
        euler.forward(50)
        euler.pendown()
        for i in range(5):
            euler.left(144)
            euler.forward(50)
        euler.penup()
        euler.forward(100)
        euler.pendown()
        for i in range(5):
            euler.left(144)
            euler.forward(50)
        euler.penup()
        euler.forward(100)
        euler.pendown()
        for i in range(5):
            euler.left(144)
            euler.forward(50)
        euler.penup()
        euler.forward(100)
        euler.pendown()
        
    def letter_N(turtle):
        sherva.backward(200)
        sherva.clear()
        sherva.left(90)
        sherva.forward(100)
        sherva.right(150)
        sherva.forward(110)
        sherva.left(150)
        sherva.forward(100)
        sherva.up()
        # next letter
        sherva.right(90)
        sherva.forward(50)
        sherva.down()
    def letter_I(turtle):
        sherva.forward(100)
        sherva.backward(50)
        sherva.right(90)
        sherva.forward(100)
        sherva.left(90)
        sherva.backward(50)
        sherva.forward(100)
        sherva.up()
        sherva.forward(50)
        sherva.down()
    def letter_K(turtle):
        sherva.left(90)
        sherva.forward(100)
        sherva.backward(50)
        sherva.right(45)
        sherva.forward(75)
        sherva.backward(75)
        sherva.right(90)
        sherva.forward(75)
        sherva.left(45)
        sherva.up()
        sherva.forward(50)
        sherva.down()
    def letter_H(turtle):
        sherva.left(90)
        sherva.forward(100)
        sherva.backward(50)
        sherva.right(90)
        sherva.forward(50)
        sherva.left(90)
        sherva.forward(50)
        sherva.backward(100)
        #
        sherva.up()
        sherva.right(90)
        sherva.forward(50)
        sherva.left(90)
        sherva.forward(100)
        sherva.right(90)
        sherva.down()
        #
    def letter_i(turtle):
        sherva.forward(100)
        sherva.backward(50)
        sherva.right(90)
        sherva.forward(100)
        sherva.left(90)
        sherva.backward(50)
        sherva.forward(100)
        sherva.up()
        sherva.forward(50)
        sherva.left(90)
        sherva.down()
    def letter_L(turtle):
        sherva.forward(100)
        sherva.backward (100)
        sherva.right (90)
        sherva.forward (75)
        sherva.up()
        sherva.right(90)
        sherva.forward(200)
        sherva.down()
    sherva.end_fill()
    def shapes(turtle):
        sherva.color('blue','red')
        sherva.begin_fill()
        for i in range(5):
            sherva.left(144)
            sherva.forward(50)
        sherva.up()
        sherva.forward(75)
        sherva.down()
        for i in range(4):
            sherva.forward(50)
            sherva.right(90)
            sherva.up()
        sherva.forward(75)
        sherva.down()
        for i in range(3):
            sherva.forward(50)
            sherva.left(120)
        sherva.end_fill()
        sherva.up()
        sherva.right(90)
        sherva.forward(400)
        sherva.down()
        for i in range(5):
            sherva.left(144)
            sherva.forward(50)
        sherva.up()
        sherva.right(90)
        sherva.forward(200)
        sherva.down()
        sherva.circle(30)
        sherva.right(90)
        sherva.forward(100)
        sherva.right(90)
        sherva.forward(50)
        sherva.backward(50)
        sherva.left(90)
        sherva.forward(40)
        sherva.right(90)
        sherva.forward(50)
        sherva.penup()
        sherva.right(90)
        sherva.forward(100)
        sherva.pendown()

       


    euler_drwing(euler)
    letter_N(sherva)
    letter_I(sherva)
    letter_K(sherva)
    letter_H(sherva)
    letter_i(sherva)
    letter_L(sherva)
    shapes(sherva)
   
main()

